version: '3'
services:
  consul:
    image: consul:0.8.3
    deploy:
      resources:
        limits:
          memory: 100M
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8501:8501"
      - "8600:8600"
  rabbitmq:
    build: ./rabbitmq
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "5672:5672"
      - "15672:15672"
  keycloak:
    image: jboss/keycloak:3.1.0.Final
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin 
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "8080:8080"
